### ISSUE TITLE
Encountered TooSlowError in pyclient_tests_udp as part of CI Checks 

### ISSUE THREAD

**Issue by saiakhil2012** [vmware/concord-bft#1195]
Encountered the `TooSlowError` error in the test, `pyclient_tests_udp` in `Build and Test` check of CI checks for the PR
Link to run where it failed - https://github.com/vmware/concord-bft/pull/1194/checks?check_run_id=1865803092

Steps to reproduce the behavior: Most probably this is happening because of slow startup and there was nothing in the changes introduced by PR to make it slow, so it would be a transient error

Proposed Solution: Increase in the timeout, so that new PRs would not face this problem

**Comment by andrewjstone** [comment]
@glevkovich @yontyon We should discuss this. I'm actually surprised it doesn't fail more frequently. In this case the primary comes up only 43ms before the test fails. I think the line where the failure is occuring: ` await udp_client.sendSync(self.writeRequest(1), False)` is essentially just a check to see that the cluster is up and running. This should have a longer timeout for the client request, that we can wrap in a helper  function. Then it should be just 1 second for the` MofN` request, which is the actual target of the test. 

We can reuse the wrapper function with longer request in other tests such as `_testPrimaryWrite` also. 

Does this make sense to you guys?

**Comment by glevkovich** [comment]
@andrewjstone , this happened this week to @Liorgal28.
Lior , I had the idea that you solve it? not committed yet?

**Comment by Liorgal28** [comment]
I had another issue with UDP, but I saw this failure also.

**Comment by teoparvanov** [comment]
Hi @saiakhil2012 @andrewjstone @glevkovich @Liorgal28 , currently @yontyon is working on a fix as part of PR https://github.com/vmware/concord-bft/pull/1197

**Comment by andrewjstone** [comment]
I believe this has been fixed.
