### ISSUE TITLE
-Werror results in compilation error on macos

### ISSUE THREAD

**Issue by no2chem** [vmware/concord-bft#131]
**Describe the bug**
When building on macos (10.14.15), compilation of corebft fails due to assertions in cryptopp. I haven't tested if the behavior occurs on other platforms, but this appears related to clang and #129

update: this seems to be directly related to #129 and clang, BUILD_TESTING isn't required

```
In file included from /concord-bft/bftengine/src/bftengine/PrePrepareMsg.cpp:11:
In file included from /concord-bft/bftengine/src/bftengine/Crypto.hpp:13:
In file included from /usr/local/include/cryptopp/dll.h:17:
In file included from /usr/local/include/cryptopp/aes.h:9:
In file included from /usr/local/include/cryptopp/rijndael.h:11:
/usr/local/include/cryptopp/seckey.h:180:32: error: extra ';' inside a class [-Werror,-Wextra-semi]
        CRYPTOPP_COMPILE_ASSERT(Q > 0);
                                      ^
/usr/local/include/cryptopp/seckey.h:181:37: error: extra ';' inside a class [-Werror,-Wextra-semi]
        CRYPTOPP_COMPILE_ASSERT(N % Q == 0);
                                           ^
/usr/local/include/cryptopp/seckey.h:182:37: error: extra ';' inside a class [-Werror,-Wextra-semi]
        CRYPTOPP_COMPILE_ASSERT(M % Q == 0);
```

**To Reproduce**
Configure the project on macos and build.
```
cmake ..
make
```

**Expected behavior**
The project should build.

**Comment by no2chem** [comment]
As an update, it seems BUILD_TESTING isn't required. It might have to do with the really old version of cryptopp suggested by the readme: CRYPTOPP_5_6_5

**Comment by salieri11** [comment]
@no2chem we don't support MacOS as for now, I prefer to tackle MacOS support as a bigger PR, where everything should be tested - ability to run tests etc. I think that there are few dependencies that should be installed differently on MacOS, I suggest to defer this issue

**Comment by no2chem** [comment]
I don't think this is a macos issue. This is just an issue with building with clang with -Wall.

**Comment by upshaw-alex** [comment]
Can you confirm this is not a MacOS issue by reproducing this on a Linux VM if you do not think it is a MacOS issue?

**Comment by no2chem** [comment]
@upshaw-alex it's actually a macos issue, I take that back. Either way @beerriot suggested a fix --- I recommend to take it, as everything was working fine on macos before. Better to start that way then to try to patch should you decide to support macos in the future.

**Comment by salieri11** [comment]
Closing as we don't support native OSx build
