### ISSUE TITLE
‘ConcordAssert’ was not declared

### ISSUE THREAD

**Issue by ujnss** [vmware/concord-bft#1332]
**Describe the bug**

When I tried compile with `-DBUILD_COMM_TCP_PLAIN=ON`, I encountered the following errors:

```sh
/root/abc/concord-bft/communication/src/PlainTcpCommunication.cpp:674:7: error: ‘ConcordAssert’ was not declared in this scope
       ConcordAssert(results != tcp::resolver::iterator());
```

Thanks.

**Comment by andrewjstone** [comment]
HI @ujnss thanks for the report. It's understandable you'd have problems with the build given the instructions in the README. 
We don't support building directly with cmake anymore. The currently supported way to build is using the [docker build](https://github.com/vmware/concord-bft#docker). You can enable TCP builds by directly editing the Makefile currently or using a MakefileCustom that gets included by the Makefile.

As neither of these options are ideal for casual usage and testing, I am going to go ahead and expose all the Cmake parameters directly on the command line in a PR today. I will also update the README to clarify the build process around Docker.

I hope this helps.

**Comment by ujnss** [comment]
Thanks for your reply, I got it. It's working now.

**Comment by andrewjstone** [comment]
> Thanks for your reply, I got it. It's working now.

Great! I'm very glad to hear that.
