### ISSUE TITLE
Stable branch

### ISSUE THREAD

**Issue by adithyabhatkajake** [vmware/concord-bft#1418]
I am looking for a stable branch that compiles inside the Docker image. I wanted to test some cryptographic optimizations. I tried the `master` branch and the `v0.10.x` branches.

**Steps to Reproduce**
General build:
1. cd into the cloned repo: `cd concord-bft`
2. build the container: `docker build -t sbft .`
3. Exec a shell in the container (I use visual studio code for this)
4. Create the build directory and cd into it: `mkdir build; cd build`
5. Try building `cmake .. && make -j7`
 
**Expected behavior**
Everything should compile without errors.

**Logs**
- [ ] Make error when building the `master` branch: 
[make-master-errors.log](https://github.com/vmware/concord-bft/files/6388325/make-master-errors.log)
- [ ] Cmake error when building the `v0.10.x` branch: (Solved partially when I rebuilt the container)
[make-v0.10.x-errors.log](https://github.com/vmware/concord-bft/files/6388536/make-v0.10.x-errors.log)

**Comment by adithyabhatkajake** [comment]
I forgot to re-build the container when I changed the branch. With the rebuilt container, v0.10.x​ has the same error as the master branch.

**Comment by salieri11** [comment]
Hi @adithyabhatkajake. Can you please run `make` from `concord-bft` folder and update this ticket with the result?

**Comment by f-squirrel** [comment]
@adithyabhatkajake , please follow the instructions from [README](https://github.com/vmware/concord-bft#docker).

**Comment by guyg8** [comment]
Hi @adithyabhatkajake.  
I've also encountered the same problem. It can be solved by playing with the cmake arguments.
For example, replace "cmake .." with "CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=TRUE -DBUILD_COMM_TCP_PLAIN=FALSE -DBUILD_COMM_TCP_TLS=TRUE -DCMAKE_CXX_FLAGS_RELEASE=-O3 -g -DUSE_LOG4CPP=TRUE -DBUILD_ROCKSDB_STORAGE=TRUE -DUSE_S3_OBJECT_STORE=TRUE -DUSE_OPENTRACING=TRUE -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DOMIT_TEST_OUTPUT=FALSE -DKEEP_APOLLO_LOGS=TRUE -DBUILD_SLOWDOWN=FALSE -DBUILD_KVBC_BENCH=TRUE -DLEAKCHECK=FALSE -DTHREADCHECK=FALSE .."
(These arguments are used in the docker build.)
