### ISSUE TITLE
Clean Thread Local Storage over the code

### ISSUE THREAD

**Issue by salieri11** [vmware/concord-bft#148]
**Is your feature request related to a problem? Please describe.**
TLS hasn't been used by the library anymore

**Describe the solution you'd like**
Remove all TLS dependencies

**Comment by upshaw-alex** [comment]
I'm wondering if you should write out "Thread Local Storage" or use some other abbreviation than "TLS". IIRC "TLS" is aliased with "Transport Layer Security", and when I first read the description for this issue, I thought to myself "Wait, why are we removing TLS?" until I re-read the title and realized what you meant.

**Comment by jaybny** [comment]
i do have past experiences with compilers puking at thread local storage. if i recall. so i would ack removing dangling work for the compilers.

**Comment by salieri11** [comment]
Done
