### ISSUE TITLE
Replace printf with standard logger

### ISSUE THREAD

**Issue by salieri11** [vmware/concord-bft#149]
There are leftovers in the code where we use printf instead of logger. We need to get rid of all these printf calls.

**Comment by upshaw-alex** [comment]
The description for this issue looks like an issue template that has not been specialized for this specific issue.

**Comment by lazaridiscom** [comment]
@salieri11, is there a construct within looger that can be uses as a drop-in replacement for `printf`?

Kind of `logger::printf`?

Or do you have some concrete construct of logger in mind?
