### ISSUE TITLE
Introduce conan.io as the package management for the project

### ISSUE THREAD

**Issue by salieri11** [vmware/concord-bft#150]
## Summary
We would like to start using conan.io for package management

 ## Motivation
* To get rid of manual installs of the dependencies
* Enable repeatable builds
* Allow users to install binary packages

 ## Detailed Design
* Added package manager manager to cmake
* Convert submodules to conan packages
* Set up managed repository
 
 ## Drawbacks
* Complexity of having an extra tool
 
 ## Alternatives
Naked cmake or another package manager
 
 ## Open Questions
NA

**Comment by lazaridiscom** [comment]
@salieri11 . done within #355, should be closable.
