### ISSUE TITLE
Use DebugPersistentStorage instead of FileStorage for SimpleKVBC TesterReplica

### ISSUE THREAD

**Issue by andrewjstone** [vmware/concord-bft#152]
**Describe the bug**
In order to fix the skvbc tests, I added file persistence for bft metadata to the SimpleKVBC TesterReplica. However, the application state itself is not persisted. This is confusing, and can potentially lead to weird errors. The file persistence should be removed and instead, the in memory, debug persistence should be used.

Thanks to @guyg8 for catching this silly mistake on my part.

**To Reproduce**
N/A

**Expected behavior**
We should use Debug persistence flag.

**Comment by salieri11** [comment]
should be fixed by #161
