### ISSUE TITLE
Can't build the latest master branch

### ISSUE THREAD

**Issue by wizd** [vmware/concord-bft#1687]
**Describe the bug**
build failed with error

**To Reproduce**
follow the instruction in readme

**Expected behavior**
choose the native build procedure

**Screenshots**
<pre>[ 69%] Built target ClientsManager_test
[ 69%] Building CXX object bftengine/tests/testSeqNumForClientRequest/CMakeFiles/seqNumForClientRequest_test.dir/seqNumForClientRequest_test.cpp.o
[ 69%] Building CXX object bftengine/tests/messages/CMakeFiles/FullCommitProofMsg_test.dir/FullCommitProofMsg_test.cpp.o
[ 69%] Building CXX object bftengine/tests/messages/CMakeFiles/ViewChangeMsg_test.dir/ViewChangeMsg_test.cpp.o
/home/wizard/src/concord-bft/kvbc/src/categorization/block_merkle_category.cpp: In constructor ‘concord::kvbc::categorization::detail::BlockMerkleCategory::BlockMerkleCategory(const std::shared_ptr<concord::storage::rocksdb::NativeClient>&)’:
/home/wizard/src/concord-bft/kvbc/src/categorization/block_merkle_category.cpp:314:109: error: no matching function for call to ‘logging::Logger::Logger()’
 BlockMerkleCategory::BlockMerkleCategory(const std::shared_ptr<storage::rocksdb::NativeClient>& db) : db_{db} {
                                                                                                             ^
In file included from /home/wizard/src/concord-bft/logging/include/Logger.hpp:23:0,
                 from /home/wizard/src/concord-bft/kvbc/include/categorization/block_merkle_category.h:18,
                 from /home/wizard/src/concord-bft/kvbc/src/categorization/block_merkle_category.cpp:14:
/home/wizard/src/concord-bft/logging/include/Logging.hpp:101:3: note: candidate: logging::Logger::Logger(logging::LoggerImpl&)
   Logger(LoggerImpl& logger) : logger_{&logger} {}
   ^~~~~~
/home/wizard/src/concord-bft/logging/include/Logging.hpp:101:3: note:   candidate expects 1 argument, 0 provided
/home/wizard/src/concord-bft/logging/include/Logging.hpp:99:7: note: candidate: constexpr logging::Logger::Logger(const logging::Logger&)
 class Logger {
       ^~~~~~
/home/wizard/src/concord-bft/logging/include/Logging.hpp:99:7: note:   candidate expects 1 argument, 0 provided
/home/wizard/src/concord-bft/logging/include/Logging.hpp:99:7: note: candidate: constexpr logging::Logger::Logger(logging::Logger&&)
/home/wizard/src/concord-bft/logging/include/Logging.hpp:99:7: note:   candidate expects 1 argument, 0 provided
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-undefined-var-template’ [-Werror]
cc1plus: error: unrecognized command line option ‘-Wno-extra-semi’ [-Werror]
cc1plus: all warnings being treated as errors
kvbc/CMakeFiles/kvbc.dir/build.make:453: recipe for target 'kvbc/CMakeFiles/kvbc.dir/src/categorization/block_merkle_category.cpp.o' failed
make[2]: *** [kvbc/CMakeFiles/kvbc.dir/src/categorization/block_merkle_category.cpp.o] Error 1
CMakeFiles/Makefile2:3624: recipe for target 'kvbc/CMakeFiles/kvbc.dir/all' failed
make[1]: *** [kvbc/CMakeFiles/kvbc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 69%] Building CXX object bftengine/tests/messages/CMakeFiles/ViewChangeMsg_test.dir/helper.cpp.o
[ 69%] Building CXX object bftengine/tests/messages/CMakeFiles/FullCommitProofMsg_test.dir/helper.cpp.o
[ 70%] Linking CXX executable seqNumForClientRequest_test
[ 70%] Linking CXX executable ViewChangeMsg_test
[ 70%] Linking CXX executable FullCommitProofMsg_test
[ 70%] Built target seqNumForClientRequest_test
[ 70%] Built target ViewChangeMsg_test
[ 70%] Built target FullCommitProofMsg_test
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
wizard@concord-dev:~/src/concord-bft/build$ 
</pre>

**Comment by f-squirrel** [comment]
Hi @wizd, thank you for the report.
Since Concord-BFT has dependencies and multiple compilation flags, the recommended way of building Concord-BFT is using docker.
The procedure is described on the [README](https://github.com/vmware/concord-bft#install-and-build-ubuntu-linux-1804) page.

If you are willing to use the native build, please refer to the Dockerized build's [Makefile](https://github.com/vmware/concord-bft/blob/master/Makefile) to see the CMake flags enabling to build Concord-BFT.

**Comment by wizd** [comment]
ok, I'll try it. thanks
