### ISSUE TITLE
Bug in https://github.com/vmware/concord-bft/blob/dc77051f87e4c32cc7418dc4e44530d2cbc68230/bftengine/src/bftengine/PersistentStorageImp.cpp#L875

### ISSUE THREAD

**Issue by guyg7** [vmware/concord-bft#194]
The following assert is incorrect: https://github.com/vmware/concord-bft/blob/dc77051f87e4c32cc7418dc4e44530d2cbc68230/bftengine/src/bftengine/PersistentStorageImp.cpp#L875

You probably want to write "Assert(hasDescriptorOfLastExitFromView() || desc.view == 0)”

**Comment by salieri11** [comment]
Reopening to close by correct PR
