### ISSUE TITLE
Docker startup problem

### ISSUE THREAD

**Issue by SHGLya** [vmware/concord-bft#2463]
Can you give the startup documentation for docker

**Comment by teoparvanov** [comment]
Hi @SHGLya,  we have recently published a sample stand-alone application (K/V store) on top of Concord-BFT consensus here:
https://github.com/vmware/concord-bft/tree/master/examples

Running the demo should be pretty straightforward by following the [README/md](https://github.com/vmware/concord-bft/blob/master/examples/README.md)
