### ISSUE TITLE
Minimal toy example for concord-bft

### ISSUE THREAD

**Issue by matnar** [vmware/concord-bft#2519]
Concord-bft seems a very good implementation of a BFT algorithm. As such, it could be very useful to solve different kinds of problems in distributed systems.

We are evaluating whether we could use it to integrate it into our application, which can be modeled as a state machine, in order to make it resilient to Byzantine failures. Is there a guide, reference implementation, or set of tests showing what should be done to write a concord-bft-based application?

We understand that the example application you provide is "Simple Key-Value Blockchain" (SKVBC). However this is a quite advanced use case already. In order to integrate concord-bft and understand where the bounds around the BFT module are, a very basic example would be easier to reason about.

Would it be possible to add a minimal example to the project? For example, what about a replicated integer register with a single operation “increment”?

**Comment by teoparvanov** [comment]
Hello @matnar , we currently don't have a simpler demo than SKVBC. The team is working on one though, which we expect to be out in the next 1-2 months.

**Comment by teoparvanov** [comment]
Hi @matnar, as discussed previously - we have recently published a sample stand-alone application (K/V store) on top of Concord-BFT consensus here:
https://github.com/vmware/concord-bft/tree/master/examples

Let us know your thoughts.
