### ISSUE TITLE
Nodes joining and leaving dynamically 

### ISSUE THREAD

**Issue by KrishnaPG** [vmware/concord-bft#255]
Could not find any other place to raise a query, hence posting it here.

It is not clear how arbitrary nodes can join and leave the BFT consensus network on the fly.

The SimpleTest application is demonstrating few nodes with a client, but it does not seem to be considering the scenario where multiple nodes writing a value at the same time: https://github.com/vmware/concord-bft/blob/c606b297fcd83ab5e3de125be093566a37aed695/bftengine/tests/simpleTest/simple_test_client.hpp#L176 

Is that possible? Can multiple nodes:

1. update the value of same key at the same time?
2. write multiple values that belong to different keys at the same time?

If only one client is ever allowed to read/write from the nodes (as assumed in the above shown test code), then it is a very restrictive scenario that does not test the distributed nature of the nodes. Any test case that demonstrates multiple nodes writing multiple values (but everyone getting synced with one single agreed value / block of values) would be the best showcase example. Any pointers or info on those lines would be of great help.

**Comment by andrewjstone** [comment]
HI @KrishnaPG,

Currently there is no way to add or remove nodes. That is called dynamic reconfiguration, and is not yet implemented.

You are correct that simpleTest only shows writing to keys serially. We have more advanced tests using a python framework. https://github.com/vmware/concord-bft/tree/master/test

Specifically, [this test](https://github.com/vmware/concord-bft/blob/master/test/test_skvbc_chaos.py#L119) does a lot of concurrent writes and uses a linearizability checker for validation. 

We intend to add many more failures modes to this specific test in the future. 

You can also join our [slack](https://concordbft.slack.com/) and ask questions there. Just send an email to concordbft@gmail.com and someone will add you.
