### ISSUE TITLE
Looks like you have some compile time errors

### ISSUE THREAD

**Issue by timcullen2015** [vmware/concord-bft#28]
**Describe the bug**
Making in '/home/tcullen/builds/concord-bft/release' ...

[ 21%] Built target bls_relic
[ 31%] Built target common
[ 32%] Built target threshsign
[ 92%] Built target corebft
[ 93%] Linking CXX executable server
../../libcorebft.a(Crypto.cpp.o): In function `bftEngine::impl::SecretSharingOperations::recoverBinaryString(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
Crypto.cpp:(.text+0x3815): undefined reference to `CryptoPP::StringStore::TransferTo2(CryptoPP::BufferedTransformation&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
Crypto.cpp:(.text+0x39de): undefined reference to `CryptoPP::StringStore::TransferTo2(CryptoPP::BufferedTransformation&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
Crypto.cpp:(.text+0x3a2d): undefined reference to `CryptoPP::StringStore::TransferTo2(CryptoPP::BufferedTransformation&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
../../libcorebft.a(Crypto.cpp.o): In function `CryptoPP::SourceTemplate<CryptoPP::StringStore>::Pump2(unsigned long&, bool)':
Crypto.cpp:(.text._ZN8CryptoPP14SourceTemplateINS_11StringStoreEE5Pump2ERmb[_ZN8CryptoPP14SourceTemplateINS_11StringStoreEE5Pump2ERmb]+0x30): undefined reference to `CryptoPP::StringStore::TransferTo2(CryptoPP::BufferedTransformation&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
../../libcorebft.a(Crypto.cpp.o):(.data.rel.ro._ZTVN8CryptoPP11OutputProxyE[_ZTVN8CryptoPP11OutputProxyE]+0xd0): undefined reference to `CryptoPP::BufferedTransformation::Skip(unsigned long)'
../../libcorebft.a(Crypto.cpp.o):(.data.rel.ro._ZTVN8CryptoPP17SimpleProxyFilterE[_ZTVN8CryptoPP17SimpleProxyFilterE]+0xd0): undefined reference to `CryptoPP::BufferedTransformation::Skip(unsigned long)'
../../libcorebft.a(Crypto.cpp.o):(.data.rel.ro._ZTVN8CryptoPP17SimpleProxyFilterE[_ZTVN8CryptoPP17SimpleProxyFilterE]+0x120): undefined reference to `CryptoPP::Filter::TransferTo2(CryptoPP::BufferedTransformation&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
../../libcorebft.a(Crypto.cpp.o):(.data.rel.ro._ZTVN8CryptoPP17SimpleProxyFilterE[_ZTVN8CryptoPP17SimpleProxyFilterE]+0x128): undefined reference to `CryptoPP::Filter::CopyRangeTo2(CryptoPP::BufferedTransformation&, unsigned long&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const'
../../libcorebft.a(Crypto.cpp.o):(.data.rel.ro._ZTVN8CryptoPP14SourceTemplateINS_11StringStoreEEE[_ZTVN8CryptoPP14SourceTemplateINS_11StringStoreEEE]+0xd0): undefined reference to `CryptoPP::BufferedTransformation::Skip(unsigned long)'
../../libcorebft.a(Crypto.cpp.o):(.data.rel.ro._ZTVN8CryptoPP14SourceTemplateINS_11StringStoreEEE[_ZTVN8CryptoPP14SourceTemplateINS_11StringStoreEEE]+0x120): undefined reference to `CryptoPP::Filter::TransferTo2(CryptoPP::BufferedTransformation&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
../../libcorebft.a(Crypto.cpp.o):(.data.rel.ro._ZTVN8CryptoPP14SourceTemplateINS_11StringStoreEEE[_ZTVN8CryptoPP14SourceTemplateINS_11StringStoreEEE]+0x128): undefined reference to `CryptoPP::Filter::CopyRangeTo2(CryptoPP::BufferedTransformation&, unsigned long&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const'
../../libcorebft.a(Crypto.cpp.o):(.data.rel.ro._ZTVN8CryptoPP12StringSourceE[_ZTVN8CryptoPP12StringSourceE]+0xd0): undefined reference to `CryptoPP::BufferedTransformation::Skip(unsigned long)'
../../libcorebft.a(Crypto.cpp.o):(.data.rel.ro._ZTVN8CryptoPP12StringSourceE[_ZTVN8CryptoPP12StringSourceE]+0x120): undefined reference to `CryptoPP::Filter::TransferTo2(CryptoPP::BufferedTransformation&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
../../libcorebft.a(Crypto.cpp.o):(.data.rel.ro._ZTVN8CryptoPP12StringSourceE[_ZTVN8CryptoPP12StringSourceE]+0x128): undefined reference to `CryptoPP::Filter::CopyRangeTo2(CryptoPP::BufferedTransformation&, unsigned long&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const'
collect2: error: ld returned 1 exit status
bftengine/tests/simpleTest/CMakeFiles/simpleTest_server.dir/build.make:122: recipe for target 'bftengine/tests/simpleTest/server' failed
make[2]: *** [bftengine/tests/simpleTest/server] Error 1
CMakeFiles/Makefile2:371: recipe for target 'bftengine/tests/simpleTest/CMakeFiles/simpleTest_server.dir/all' failed
make[1]: *** [bftengine/tests/simpleTest/CMakeFiles/simpleTest_server.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**To Reproduce**
make.sh

**Expected behavior**
What is expected to happen is that compilation completes without error or warning.

**Screenshots**

**Comment by beerriot** [comment]
Thanks for the bug report, @timcullen2015!

Could you please confirm:
1. What version of cryptopp you have installed?
2. Which compiler you're using?

I don't see this error with cryptopp 5.6.5 and gcc 5.4:

```
$ grep Library /usr/local/include/cryptopp/cryptlib.h
/*!	\mainpage Crypto++ Library 5.6.5 API Reference
$ ls /usr/local/lib/libcryptopp.so.*
/usr/local/lib/libcryptopp.so.5.6
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
```

**Comment by guyg8** [comment]
The problem appears to be related to code that is not used by the current version (it related to functionality that I did not include in this repo). If this is a real problem, we can delete the problematic code from bftengine/Crypto.cpp

**Comment by salieri11** [comment]
@timcullen2015 Are you still having trouble with build?
