### ISSUE TITLE
Add a README.md to kvbc directory

### ISSUE THREAD

**Issue by andrewjstone** [vmware/concord-bft#293]
**Is your feature request related to a problem? Please describe.**
All top level directories should have a brief readme to explain what they do.

**Describe the solution you'd like**
Write a README.md that talks about the code in the directory, what it is used for and how it is structured. It doesn't need to be more than a few lines + bullets.

**Describe alternatives you've considered**
The alternative is to not document our top level directories. 

**Additional context**
N/A

**Comment by teoparvanov** [comment]
I agree with the README part, but if kvbc/ is to remain with concord-bft, it should be covered by automated tests & CI (currently this is not the case AFAIK). 

Nothing too fancy though - maybe just basic K/V operations would be enough, as BFT consensus is already validated by the current Python system tests.

**Comment by lazaridiscom** [comment]
The README should be added (and if tests are missing, this can be mentioned in the readme, pointing to an related open issue).

**Comment by andrewjstone** [comment]
We know we need more docs. We started documenting KVBC and will add more. This is an outdated example issue that is superfluous.
