### ISSUE TITLE
SkvbcPersistenceTest fails intermittently (in CI & locally)

### ISSUE THREAD

**Issue by teoparvanov** [vmware/concord-bft#294]
**Describe the bug**
As stated in the title, there are intermittent failures of persistence-related system tests.
Most of the failures seem to be related to the fact that we restart replicas and some of the metrics aren't immediately available. However other failures have been observed too, including failing assertions in the concord-bft code (see attached stack traces).

**To Reproduce**

- in CI it happens approx. 1 out of 10 times - cannot be reproduced deterministically
- when running the system tests locally (Ubuntu 18.04), failures can be observed by running the following shell command:
``for i in `seq 20`; do python3 -m unittest test_skvbc_persistence.SkvbcPersistenceTest.test_st_while_primary_crashes 1>/dev/null; done``

**Expected behavior**
SkvbcPersistenceTest should succeed consistently.

**Screenshots**
N/A

**Comment by teoparvanov** [comment]
[observed_stacktraces.txt](https://github.com/vmware/concord-bft/files/3920914/observed_stacktraces.txt)

**Comment by teoparvanov** [comment]
After introducing the following PR https://github.com/vmware/concord-bft/pull/295 we could observe the following failure (possibly an actual ST bug):

[stacktrace_possible_st_bug.txt](https://github.com/vmware/concord-bft/files/3921038/stacktrace_possible_st_bug.txt)

**Comment by teoparvanov** [comment]
PR https://github.com/vmware/concord-bft/pull/289 aims to solve the intermittent failures caused by flaky test logic. 

Note: this PR does not try to address potential concord-bft issues.

**Comment by teoparvanov** [comment]
Here's another intermittent failure instance:
[stacktrace_keyerror.txt](https://github.com/vmware/concord-bft/files/3927775/stacktrace_keyerror.txt)

**Comment by teoparvanov** [comment]
Most of the failures are observed when wait_for_state_transfer_to_stop() is invoked on a random "stable" replica towards the end of _run_state_transfer_while_crashing_primary_repeatedly().

To make the test more reliable, we should remove this random aspect and make sure we select an "up_to_date" replica which has not been recently restarted, so that it has all its metrics ready.

**Comment by teoparvanov** [comment]
The last remaining failure is due to an assert in ReplicaLoader.cpp which fails occasionally (while filling up the SKVBC with data and waiting for checkpoints):

VerifyOR(seqNum > ld.lastStableSeqNum, e.getCheckpointMsg()->isStableState(), InconsistentErr);

We should add some logging to understand what's going on here, but the problem could be due to the strict inequality between seqNum and ld.lastStableSeqNum.

IMO (discussed with Yulia), the following change could help:
seqNum **>=** ld.lastStableSeqNum

**Comment by yuliasherman** [comment]
We don't need additional logging. asserUtils.hpp does this job for us. We need just a replica log file, which includes information which parameters caused the assert to throw.

**Comment by teoparvanov** [comment]
Thanks @yuliasherman, this would help indeed! However, to make it work, we need to run CI with log4cpp (USE_LOG4CPP=ON), which is not the case right now...

**Comment by yuliasherman** [comment]
Oh, got your point now.

**Comment by teoparvanov** [comment]
Yulia's [fix](https://github.com/yuliasherman/concord-bft/commit/e7471ec0ce5cf61b508fec2a88b4f6ac36ea998a) seems to resolve the last intermittent failures.

Observing for several days and closing if not reproduced anymore...

**Comment by teoparvanov** [comment]
Closing this issue, as it hasn't been observed after the above fix.
