### ISSUE TITLE
[PROJECT] Add Milestones, remove "Projects" and "Wiki"

### ISSUE THREAD

**Issue by ghost** [vmware/concord-bft#439]
Though there are not many open issues, a Milestone (minimum 1.0, possibly more) could be added to get a sense of a roadmap. This has an additional benefit of  making the project look more "alive".

The "wiki" seems unused (doesn't open for me), so possibly just remove.

The same for the "Projects" tab.

**Comment by salieri11** [comment]
closing as irrelevant
