### ISSUE TITLE
Memory leak at  PartialProofsSet::tryToCreateFullProof

### ISSUE THREAD

**Issue by cloudnoize** [vmware/concord-bft#501]
**Describe the bug**
At _PartialProofsSet::tryToCreateFullProof()_
the line -  _IThresholdAccumulator* acc = thresholdAccumulator->clone()_
creates a new object by calling  - 
_virtual IThresholdAccumulator* clone() { return new BlsThresholdAccumulator(*this); } (file BlsThresholdAccumulator.h)_

The pointer is being passed to AsynchProofCreationJob for async execution, but I don't see any code that deletes it.

**Expected behavior**
delete the created object by using  std ::unique_ptr

**Comment by cloudnoize** [comment]
Actually the issue is even more profound, Since the job that wraps the  IThresholdAccumulator, AsynchProofCreationJob , doesn't get deleted after its execution.

**Comment by teoparvanov** [comment]
This code has been refactored, and therefore the issue is no longer applicable.
