### ISSUE TITLE
compile error--clang: error: unsupported option '--no-system-header-prefix'

### ISSUE THREAD

**Issue by zzpp3377** [vmware/concord-bft#67]
ubuntu 14.04
clang： 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
gcc：4.8.4

when i run make，i got an error：

Scanning dependencies of target bls_relic
[  1%] Building CXX object threshsign/src/bls/relic/CMakeFiles/bls_relic.dir/BlsAccumulatorBase.cpp.o
clang: error: unsupported option '--no-system-header-prefix'
clang: error: no such file or directory: 'relic'
make[2]: *** [threshsign/src/bls/relic/CMakeFiles/bls_relic.dir/BlsAccumulatorBase.cpp.o] Error 1
make[1]: *** [threshsign/src/bls/relic/CMakeFiles/bls_relic.dir/all] Error 2
make: *** [all] Error 2

I have installed clang，relic，cryptopp. 
I need some help. Thanks.

**Comment by andrewjstone** [comment]
Hi @zzpp3377 

Clang 3.4 doesn't support that build option. Please use a later version of ubuntu. We currently only test and support 18.04, although later versions may work.

I just opened a PR to add the Ubuntu version to the documentation.

**Comment by zzpp3377** [comment]
thank you @andrewjstone 。
According to your answer， i used a ubuntu 18.04 container on ubuntu 14.04.
kernel：3.13.0-39-generic
Fortunately，the 3.13 kernel and ubuntu 18.04 work well.
In container，I run make Successfully.

**Comment by andrewjstone** [comment]
You're welcome @zzpp3377. Glad it works for you.
