### ISSUE TITLE
Unrecognized symbols 'CMP_EQ' and 'BN_POS'

### ISSUE THREAD

**Issue by cnnrznn** [vmware/concord-bft#88]
**Describe the bug**
Failing to build in Ubuntu:Xenial with the error message as in the title (screenshot attached)

**To Reproduce**
I have attached my Dockerfile used to build a concord-bft image.
Ignore everything past line 59.
The bug occurs at line 58.

[systems_concord-bft_Dockerfile.txt](https://github.com/vmware/concord-bft/files/3163097/systems_concord-bft_Dockerfile.txt)

**Expected behavior**
Compile concord-bft successfully

**Screenshots**

![concord_bug](https://user-images.githubusercontent.com/8882693/57469619-0d27a780-7255-11e9-8577-efc31a969c7c.PNG)

**Comment by guyg7** [comment]
Looks like we have conflicts with the latest updates in relic. We will fix this problem soon.
In the meantime, I suggest using the relic version from February 1 (commit b984e901ba78c83ea4093ea96addd13628c8c2d0  ,  https://github.com/relic-toolkit/relic/tree/b984e901ba78c83ea4093ea96addd13628c8c2d0 ).

**Comment by cnnrznn** [comment]
Thanks! This has resolved the issue and the system is churning. Closing
